// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNWADMNcGOR2eVtmN4UbiwHi2xtOyw0eU',
    appId: '1:218293764392:web:1b5c0ed657a5a9dcf8101d',
    messagingSenderId: '218293764392',
    projectId: 'mpuza-na-muganga',
    authDomain: 'mpuza-na-muganga.firebaseapp.com',
    storageBucket: 'mpuza-na-muganga.firebasestorage.app',
    measurementId: 'G-GESCTDML45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lJRNVeYpRoSyfne1xcVZeSHlxmTYQWY',
    appId: '1:218293764392:android:f0bd1fde77855815f8101d',
    messagingSenderId: '218293764392',
    projectId: 'mpuza-na-muganga',
    storageBucket: 'mpuza-na-muganga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXX6arYOqJ-jPPoUfeG0RBXymsALbfJEk',
    appId: '1:218293764392:ios:4b7df980ffc014b8f8101d',
    messagingSenderId: '218293764392',
    projectId: 'mpuza-na-muganga',
    storageBucket: 'mpuza-na-muganga.firebasestorage.app',
    iosBundleId: 'com.example.sCuruza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXX6arYOqJ-jPPoUfeG0RBXymsALbfJEk',
    appId: '1:218293764392:ios:4b7df980ffc014b8f8101d',
    messagingSenderId: '218293764392',
    projectId: 'mpuza-na-muganga',
    storageBucket: 'mpuza-na-muganga.firebasestorage.app',
    iosBundleId: 'com.example.sCuruza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNWADMNcGOR2eVtmN4UbiwHi2xtOyw0eU',
    appId: '1:218293764392:web:5c78f9b4a864926cf8101d',
    messagingSenderId: '218293764392',
    projectId: 'mpuza-na-muganga',
    authDomain: 'mpuza-na-muganga.firebaseapp.com',
    storageBucket: 'mpuza-na-muganga.firebasestorage.app',
    measurementId: 'G-6CS8NGE3L8',
  );
}
