# Generated by Django 5.2.8 on 2025-11-28 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('DAY', 'Day'), ('EVENING', 'Evening')], max_length=20)),
                ('intake', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('current_status', models.CharField(default='Beginner', max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('date_recorded', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission_method', models.CharField(choices=[('API', 'API'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The Learning Assistant who entered this', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_sessions', to='core.student')),
                ('tool_source', models.ForeignKey(blank=True, help_text='If API, which tool?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.externaltool')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('best_wpm', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
